// Temples & Towns — client-editable data
// Update properties[], rooms{}, and reviews[] below when the client provides real content.
// Images: place files in /images/ and update the placeholder/label keys.

window.WA_URL = 'https://api.whatsapp.com/send/?phone=918553441449&text=Hi%2C+I%27d+like+to+chat+about+Temple+and+Towns+Resorts.&type=phone_number&app_absent=0';

window.TT_DATA = {
  cities: [
    {
      slug: 'pondicherry',
      name: 'Pondicherry',
      tag: 'French quarter, slow mornings',
      hue: 210,
    },
    {
      slug: 'bengaluru',
      name: 'Bengaluru',
      tag: 'Garden city, modern stays',
      hue: 220,
    },
  ],
  properties: [
    {
      id: 'p1',
      city: 'pondicherry',
      name: 'Maison Auroville',
      area: 'White Town · Rue Suffren',
      blurb: 'A restored colonial villa with shaded courtyards and a quiet pool.',
      rating: 4.8,
      reviews: 312,
      from: 7400,
      placeholder: 'colonial villa exterior, courtyard',
      tone: 'oklch(0.88 0.04 230)',
    },
    {
      id: 'p2',
      city: 'pondicherry',
      name: 'The Promenade House',
      area: 'Goubert Avenue · Seafront',
      blurb: 'Sea-view rooms steps from the Promenade with fresh-baked mornings.',
      rating: 4.7,
      reviews: 189,
      from: 9200,
      placeholder: 'seafront balcony view, palms',
      tone: 'oklch(0.9 0.04 215)',
    },
    {
      id: 'p3',
      city: 'pondicherry',
      name: 'Le Jardin d\'Eau',
      area: 'Mission Street · Heritage',
      blurb: 'Bougainvillea-filled garden hotel with hand-built bohra beds.',
      rating: 4.6,
      reviews: 144,
      from: 5800,
      placeholder: 'garden hotel courtyard',
      tone: 'oklch(0.88 0.04 200)',
    },
    {
      id: 'p4',
      city: 'bengaluru',
      name: 'Cubbon House',
      area: 'Cubbon Park · MG Road',
      blurb: 'Modernist boutique with rooftop bar overlooking the park canopy.',
      rating: 4.7,
      reviews: 421,
      from: 8200,
      placeholder: 'modern boutique facade',
      tone: 'oklch(0.88 0.04 235)',
    },
    {
      id: 'p5',
      city: 'bengaluru',
      name: 'Indiranagar Quarters',
      area: '12th Main · Indiranagar',
      blurb: 'Loft-style suites above the city\'s best coffee and bookstores.',
      rating: 4.5,
      reviews: 278,
      from: 6400,
      placeholder: 'loft suite interior',
      tone: 'oklch(0.9 0.04 220)',
    },
    {
      id: 'p6',
      city: 'bengaluru',
      name: 'Whitefield Atrium',
      area: 'Whitefield · Tech Park',
      blurb: 'Long-stay residences with pool, gym, and quiet workspaces.',
      rating: 4.6,
      reviews: 506,
      from: 7100,
      placeholder: 'residence atrium pool',
      tone: 'oklch(0.88 0.04 245)',
    },
  ],
  rooms: {
    p1: [
      { id: 'r1a', type: 'Garden Standard', capacity: 2, price: 7400, beds: '1 Queen', size: '24 m²', amenities: ['Wi-Fi', 'AC', 'Garden view', 'Filter coffee'] },
      { id: 'r1b', type: 'Courtyard Deluxe', capacity: 3, price: 9800, beds: '1 King', size: '32 m²', amenities: ['Wi-Fi', 'AC', 'Courtyard balcony', 'Bath tub', 'Breakfast'] },
      { id: 'r1c', type: 'Heritage Suite', capacity: 4, price: 14200, beds: '1 King + 1 Twin', size: '48 m²', amenities: ['Wi-Fi', 'AC', 'Private terrace', 'Lounge', 'Breakfast', 'Airport pickup'] },
    ],
    p2: [
      { id: 'r2a', type: 'Sea-Facing Standard', capacity: 2, price: 9200, beds: '1 Queen', size: '26 m²', amenities: ['Wi-Fi', 'AC', 'Sea view', 'Breakfast'] },
      { id: 'r2b', type: 'Promenade Suite', capacity: 3, price: 13400, beds: '1 King', size: '40 m²', amenities: ['Wi-Fi', 'AC', 'Sea-facing balcony', 'Lounge', 'Breakfast'] },
    ],
    p3: [
      { id: 'r3a', type: 'Bougainvillea Room', capacity: 2, price: 5800, beds: '1 Queen', size: '22 m²', amenities: ['Wi-Fi', 'AC', 'Garden access'] },
      { id: 'r3b', type: 'Bohra Suite', capacity: 3, price: 8400, beds: '1 King', size: '34 m²', amenities: ['Wi-Fi', 'AC', 'Garden view', 'Hand-built furnishings'] },
    ],
    p4: [
      { id: 'r4a', type: 'Park Standard', capacity: 2, price: 8200, beds: '1 Queen', size: '24 m²', amenities: ['Wi-Fi', 'AC', 'Workspace'] },
      { id: 'r4b', type: 'Canopy Suite', capacity: 3, price: 12800, beds: '1 King', size: '38 m²', amenities: ['Wi-Fi', 'AC', 'Park view', 'Rooftop access', 'Breakfast'] },
    ],
    p5: [
      { id: 'r5a', type: 'Loft Studio', capacity: 2, price: 6400, beds: '1 Queen', size: '28 m²', amenities: ['Wi-Fi', 'AC', 'Kitchenette', 'Workspace'] },
      { id: 'r5b', type: 'Two-Bed Loft', capacity: 4, price: 11200, beds: '2 Queen', size: '46 m²', amenities: ['Wi-Fi', 'AC', 'Kitchen', 'Lounge'] },
    ],
    p6: [
      { id: 'r6a', type: 'Studio Residence', capacity: 2, price: 7100, beds: '1 Queen', size: '30 m²', amenities: ['Wi-Fi', 'AC', 'Pool', 'Gym'] },
      { id: 'r6b', type: 'One-Bedroom Residence', capacity: 3, price: 10800, beds: '1 King', size: '52 m²', amenities: ['Wi-Fi', 'AC', 'Kitchen', 'Pool', 'Gym'] },
    ],
  },
  reviews: [
    { name: 'Ananya R.', tier: 'Gold', rating: 5, text: 'The courtyard at dusk, with fairy lights and filter coffee — exactly what I needed.', when: 'Two weeks ago' },
    { name: 'Marcus L.', tier: 'Silver', rating: 5, text: 'Booking approval was fast and the host called personally to confirm dietary requests.', when: 'Last month' },
    { name: 'Priya S.', tier: 'Bronze', rating: 4, text: 'Quiet, beautiful, well-priced. Wish there were more rooms with sea view.', when: 'Last month' },
  ],
  initialBookings: [
    {
      id: 'BK-7421',
      property: 'Cubbon House',
      city: 'Bengaluru',
      room: 'Canopy Suite',
      checkIn: '2026-05-12',
      checkOut: '2026-05-15',
      nights: 3,
      guests: 2,
      total: 38400,
      state: 'confirmed',
    },
    {
      id: 'BK-7298',
      property: 'Maison Auroville',
      city: 'Pondicherry',
      room: 'Garden Standard',
      checkIn: '2026-03-02',
      checkOut: '2026-03-04',
      nights: 2,
      guests: 2,
      total: 14800,
      state: 'completed',
    },
  ],
};
